### ISSUE TITLE
error when use the demo provided by official

### ISSUE THREAD

**Issue by xycloud** [sirensolutions/kibi#30]
```
[2016-05-12 17:14:04,296][INFO ][rest.suppressed          ] /.kibi/template/kibi-json-jade Params: {index=.kibi, op_type=create, id=kibi-json-jade, type=template}
RemoteTransportException[[Grey King][127.0.0.1:9330][indices:data/write/index[p]]]; nested: DocumentAlreadyExistsException[[template][kibi-json-jade]: document already exists];
Caused by: [.kibi][[.kibi][1]] DocumentAlreadyExistsException[[template][kibi-json-jade]: document already exists]
    at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:432)
    at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:390)
    at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:362)
    at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:515)
    at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:810)
    at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
    at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157)
    at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:65)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:595)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:263)
```

**Comment by scampi** [comment]
this is the normal kibana strategy for adding objects (saved searches, visualizations, ...) to the index.

**Comment by xycloud** [comment]
but I cannot even run your demo project

**Comment by scampi** [comment]
What errors do you have ? The one you pasted is normal.

**Comment by xycloud** [comment]
log   [13:46:37.029] [warning][query_engine] Kibi index NOT found
/Downloads/kibi-0.3.2-demo-full-darwin-x64/kibi/src/plugins/kibi_core/lib/query_engine.js:90
  self._isKibiIndexPresent().then(function () {
       ^
TypeError: undefined is not a function
    at [object Object].QueryEngine.loadTemplates [as _onTimeout](/Users/Mocker/Downloads/kibi-0.3.2-demo-full-darwin-x64/kibi/src/plugins/kibi_core/lib/query_engine.js:90:8)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by scampi** [comment]
this should be fixed in the latest release https://github.com/sirensolutions/kibi/releases/tag/tag-4.4.1-1
