### ISSUE TITLE
Error with JDBC Connection

### ISSUE THREAD

**Issue by OElesin** [sirensolutions/kibi#33]
I added the JDBC connections settings on Kibi from end. But was prompted to enable the `load_jdbc: true` setting in the kibi.yml file. I did this and I get the error below when I start kibi

```
bin/kibi: line 27: bin/../bin/create_symlink.sh: Permission denied
  log   [13:21:58.842] [warning][config] Settings for "load_jdbc" were not applied, check for spelling errors and ensure the plugin is loaded.
```

Help with this

**Comment by scampi** [comment]
Try setting `kibi_core.load_jdbc` to true. We'll update the notification message to be clearer.

**Comment by OElesin** [comment]
Thanks. But this is the new error I got after adding `kibi_core.load_jdbc`

```
  log   [14:03:32.580] [error][kibi_core] Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/hdfs/kibi/node_modules/jdbc/node_modules/java/build/Release/nodejavabridge_bindings.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/hdfs/kibi/node_modules/jdbc/node_modules/java/lib/nodeJavaBridge.js:21:16)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/hdfs/kibi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/hdfs/kibi/node_modules/jdbc/node_modules/java/index.js:2:18)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/hdfs/kibi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/hdfs/kibi/node_modules/jdbc/lib/jinst.js:3:12)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/hdfs/kibi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

**Comment by szydan** [comment]
Could you tell us more about your system. Which linux distribution you are running?
Could you try to install 

```
sudo apt-get install libstdc++6
```

and try again 
If this does not help there are some additional hints here 
http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by scampi** [comment]
please reopen if you still have this error
