### ISSUE TITLE
Error when activating load jdbc : libjvm.so

### ISSUE THREAD

**Issue by eluanb** [sirensolutions/kibi#49]
Kibi Version: 4.4.2
Operating System: Linux CentOS 7
Error report in kibi configuration
kibi_core:
  load_jdbc: true

path: kibi/config/kibi.yml

Log:

```
  log   [17:06:22.246] [info][query_engine] Loading templates
  log   [17:06:22.675] [error][kibi_core] Error: libjvm.so: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/kibi-4.4.2/kibi/node_modules/jdbc/node_modules/java/lib/nodeJavaBridge.js:21:16)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/kibi-4.4.2/kibi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/kibi-4.4.2/kibi/node_modules/jdbc/node_modules/java/index.js:2:18)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/kibi-4.4.2/kibi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
  log   [17:06:22.676] [error][status][plugin:kibi_core] Status changed from yellow to red - Query engine initializiation failed
```

Error: libjvm.so: cannot open shared object file: No such file or directory
kibi/bin/java_home_lib_server -> /opt/jdk/jdk1.8.0_91/jre/lib/amd64/server
rwxrwxrwx 1 10 143 16925812 Abr  1 05:06 libjvm.so

As you can see the file exists in the libraries folder but displays error loading the kibi and the server is bad status.
If you turn off the load jdbc , the server starts smoothly.

**Comment by scampi** [comment]
Is JAVA_HOME or LD_LIBRARY_PATH set to anything ?

**Comment by eluanb** [comment]
Yes, they are informed. But I believe they are correct:

> [root@server ~]# echo $JAVA_HOME
> /opt/jdk/jdk1.8.0_91
> [root@server ~]# echo $JRE_HOME
> /opt/jdk/jdk1.8.0_91/jre
> [root@server ~]# echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/opt/jdk/jdk1.8.0_91/bin:/opt/jdk/jdk1.8.0_91/jre/bin
> [root@server ~]# echo $LD_LIBRARY_PATH 
> /opt/jdk/jdk1.8.0_91/jre/lib/amd64:/opt/jdk/jdk1.8.0_91/jre/lib/amd64/server

I'm telling something wrong?

**Comment by eluanb** [comment]
Excuse me.
I found the problem.
Due to internal security of the server variables were unset for tty/pts.
Insert variables in bash profile, and are now correct.
Server booted normally.

Thank you.

**Comment by scampi** [comment]
Great thanks for explaining what was the issue @eluanb
