### ISSUE TITLE
Visualize: Bad Gateway

### ISSUE THREAD

**Issue by asinha123** [sirensolutions/kibi#5]
I cloned the source code and try to run it using grunt dev command. Kibi started successfully but an error is flashed at the top 
Visualize: Bad Gateway
checking into more info gives this

SQLITE_CANTOPEN: unable to open database file

Error: Bad Gateway
    at respond (http://localhost:5602/bower_components/elasticsearch/elasticsearch.angular.js:38715:15)
    at checkRespForFailure (http://localhost:5602/bower_components/elasticsearch/elasticsearch.angular.js:38683:7)
    at http://localhost:5602/bower_components/elasticsearch/elasticsearch.angular.js:37321:7
    at wrappedErrback (http://localhost:5602/bower_components/angular/angular.js:11691:78)
    at wrappedErrback (http://localhost:5602/bower_components/angular/angular.js:11691:78)
    at wrappedErrback (http://localhost:5602/bower_components/angular/angular.js:11691:78)
    at http://localhost:5602/bower_components/angular/angular.js:11824:76
    at Scope.$eval (http://localhost:5602/bower_components/angular/angular.js:12811:28)
    at Scope.$digest (http://localhost:5602/bower_components/angular/angular.js:12623:31)
    at Scope.$apply (http://localhost:5602/bower_components/angular/angular.js:12915:24)

Please help.

**Comment by fabiocorneti** [comment]
Hi @asinha123,
if you don't need database access you can simply comment the following lines in `kibi.yml`:

```
#datasources:
#  crunchbase-datasource:
#    type: sqlite
#    dbfile: crunchbase.db
```

Otherwise, you can use the dataset included in the demo distributions; to do that:
- download the full or lite distribution from http://siren.solutions/kibi/download/ and uncompress
- start Elasticsearch by running `elasticsearch/bin/elasticsearch` inside the uncompressed demo distribution
- set the `elasticsearch_url` parameter in `kibi.yml` to `http://localhost:9220`
- copy the file `kibi/crunchbase.db` from the demo distribution to the root of your clone
- start Kibi by running `grunt dev`

**Comment by asinha123** [comment]
Hi fabiocorneti...it works for me.

Thanks mate
