### ISSUE TITLE
Numbers are interpreted as text in Datasource form if I modify those settings

### ISSUE THREAD

**Issue by knzwats** [sirensolutions/kibi#53]
Hello!
I tried kibi and found it very nice, but I found a weird behavior and a workaround. 
### Versions

Kibi: 4.4.2-1

Operating System: Linux version 4.4.11-23.53.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Jun 1 22:22:50 UTC 2016
### Behavior

When I create or edit MySQL datasource and set timeout/max_age to other than default number, 
properties are saved as text, which results in an error below:

TypeError: Uncaught error: msecs must be a number
    at Object.exports.enroll (timers.js:152:11)
    at Protocol._startSequence (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/Protocol.js:348:12)
    at Protocol._dequeue (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/Protocol.js:343:8)
    at Handshake.<anonymous> (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/Protocol.js:157:12)
    at emitNone (events.js:67:13)
    at Handshake.emit (events.js:166:7)
    at Handshake.Sequence.end (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/sequences/Sequence.js:99:12)
    at Handshake.Sequence.OkPacket (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ec2-user/kibi/kibi-4.4.2-1-linux-x64/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

I can manually fix the problem by removing quotes from "Objects -> datasource -> edit" menu.
#### Expected:

Those properties are saved as int when I create a datasource and leave those settings default.
I suppose it is supposed to be saved as int when I modify those properties.
#### Actual:

Modified number properties are saved as text.
### Steps to reproduce the problem

Create MySQL datasource and modify max_age/timeout, then save the settings.

Best regards!

**Comment by scampi** [comment]
thanks for reporting this issue! We'll fix that in the next 4.5.3 release that is coming any time now.

**Comment by scampi** [comment]
Fixed in 4.5.3 https://github.com/sirensolutions/kibi/releases/tag/tag-4.5.3
