### ISSUE TITLE
Application does not start on OSX - nodejs Exception

### ISSUE THREAD

**Issue by danbeck** [sirensolutions/kibi#63]
### Versions

Kibi: 4.3.5-6-darwin-x64 (CE)

Operating System:
OSX El Capitan, Version 10.11.6
### Behavior

Download and extract the zip file. Start bin/kibi. The application does not start. The following is printed on standard out:

```
  log   [09:23:40.280] [fatal] TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugins._new$ (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/src/server/plugins/PluginCollection.js:57:32)
    at tryCatch (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/dbeck/Downloads/kibi-4.5.3-6-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:136:37)
FATAL [TypeError: Cannot read property 'error' of undefined]
```

**Comment by szydan** [comment]
Hi
Could you please specify exactly which zip you've downloaded (link)
And all commands you've done to start kibi

I've tried both the empty kibi and the full demo for darwin on OSX (El Capitan 10.11.6) and they seems to work fine 

My steps are: 
For a standalone empty zip 

1) Make sure elasticsearch is running at http://localhost:9200
2) Download the zip 
3) Unzip 
4) cd kibi-4.5.3-6-darwin-x64
5) ./bin/kibi

```
$ ~/Downloads/kibi-4.5.3-6-darwin-x64
$ ./bin/kibi 
  log   [10:08:11.240] [info][status][plugin:kibana] Status changed from uninitialized to green - Ready
  log   [10:08:11.286] [info][status][plugin:elasticsearch] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [10:08:11.297] [info][status][plugin:kibi_radar_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.300] [info][status][plugin:kibi_timeline_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.307] [info][status][plugin:kibi_wordcloud_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.312] [info][status][plugin:kbn_vislib_vis_types] Status changed from uninitialized to green - Ready
  log   [10:08:11.316] [info][status][plugin:kibi_core] Status changed from uninitialized to yellow - Initialising the query engine
  log   [10:08:11.342] [info][status][plugin:kibi_data_table_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.348] [info][status][plugin:kibi_query_viewer_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.354] [info][status][plugin:kibi_sequential_join_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.357] [info][status][plugin:markdown_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.361] [info][status][plugin:elasticsearch] Status changed from yellow to green - Kibana index ready
  log   [10:08:11.363] [info][status][plugin:metric_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.374] [info][status][plugin:spyModes] Status changed from uninitialized to green - Ready
  log   [10:08:11.376] [info][status][plugin:statusPage] Status changed from uninitialized to green - Ready
  log   [10:08:11.379] [info][status][plugin:table_vis] Status changed from uninitialized to green - Ready
  log   [10:08:11.390] [info][query_engine] Found kibi index
  log   [10:08:11.393] [info][listening] Server running at http://0.0.0.0:5606
  log   [10:08:11.405] [info][query_engine] Loading templates
  log   [10:08:11.430] [warning][query_engine] Template [kibi-json-jade] already exists
  log   [10:08:11.432] [warning][query_engine] Template [kibi-table-jade] already exists
  log   [10:08:11.437] [info][query_engine] Reloading 1 queries into memory:
  log   [10:08:11.437] [info][query_engine] Reloading [Kibi-Graph-Query]
  log   [10:08:11.438] [warning][query_engine] Template [kibi-table-handlebars] already exists
  log   [10:08:11.445] [error][query_engine] This datasource type [tinkerpop3] - requires Kibi Enterprise Edition
  log   [10:08:11.461] [info][kibi_core] { message: 'QueryEngine initialized successfully.' }
  log   [10:08:11.462] [info][status][plugin:kibi_core] Status changed from yellow to green - Query engine initialized
```

For a full demo zip 

1) Download the zip 
2) Unzip 
3) cd elasticsearch
4) ./bin/elasticsearch
5) cd kibi
5) ./bin/kibi

```
$ ~/Downloads/kibi-4.5.3-6-darwin-x64-demo-full/kibi
$ ./bin/kibi 
  log   [10:06:27.831] [info][status][plugin:kibana] Status changed from uninitialized to green - Ready
  log   [10:06:27.868] [info][status][plugin:elasticsearch] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [10:06:27.879] [info][status][plugin:kibi_radar_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.882] [info][status][plugin:kibi_timeline_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.888] [info][status][plugin:kibi_wordcloud_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.893] [info][status][plugin:kbn_vislib_vis_types] Status changed from uninitialized to green - Ready
  log   [10:06:27.896] [info][status][plugin:kibi_core] Status changed from uninitialized to yellow - Initialising the query engine
  log   [10:06:27.904] [info][status][plugin:kibi_data_table_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.913] [info][status][plugin:kibi_query_viewer_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.917] [info][status][plugin:kibi_sequential_join_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.920] [info][status][plugin:markdown_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.923] [info][status][plugin:metric_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.925] [info][status][plugin:elasticsearch] Status changed from yellow to green - Kibana index ready
  log   [10:06:27.928] [info][status][plugin:spyModes] Status changed from uninitialized to green - Ready
  log   [10:06:27.932] [info][status][plugin:statusPage] Status changed from uninitialized to green - Ready
  log   [10:06:27.934] [info][status][plugin:table_vis] Status changed from uninitialized to green - Ready
  log   [10:06:27.949] [info][listening] Server running at http://localhost:5606
  log   [10:06:27.956] [info][query_engine] Found kibi index
  log   [10:06:27.990] [info][query_engine] Loading templates
  log   [10:06:28.007] [warning][query_engine] Template [kibi-table-jade] already exists
  log   [10:06:28.009] [warning][query_engine] Template [kibi-table-handlebars] already exists
  log   [10:06:28.010] [info][query_engine] Reloading 10 queries into memory:
  log   [10:06:28.011] [info][query_engine] Reloading [Companies-in-the-same-domain]
  log   [10:06:28.012] [info][query_engine] Reloading [Companies-"With-competitors"]
  log   [10:06:28.013] [info][query_engine] Reloading [Kibi-Graph-Query]
  log   [10:06:28.013] [info][query_engine] Reloading [Top-investors-by-count-of-investments]
  log   [10:06:28.014] [info][query_engine] Reloading [Top-investors-of-a-given-type-by-count-of-investments]
  log   [10:06:28.014] [info][query_engine] Reloading [Top-investors-from-given-country-by-investment-count]
  log   [10:06:28.015] [info][query_engine] Reloading [Top-50-companies-(HR-count)]
  log   [10:06:28.018] [info][query_engine] Reloading [Company-Info]
  log   [10:06:28.018] [info][query_engine] Reloading [Top-500-companies-(HR-count)]
  log   [10:06:28.019] [info][query_engine] Reloading [Company-Competitors]
  log   [10:06:28.022] [warning][query_engine] Template [kibi-json-jade] already exists
  log   [10:06:28.030] [error][query_engine] This datasource type [tinkerpop3] - requires Kibi Enterprise Edition
  log   [10:06:28.041] [info][kibi_core] { message: 'QueryEngine initialized successfully.' }
  log   [10:06:28.042] [info][status][plugin:kibi_core] Status changed from yellow to green - Query engine initialized
```

**Comment by danbeck** [comment]
I downloaded the following version: https://support.siren.solutions/support/solutions/articles/17000032306-kibi-4-5-3-6-community-edition. Full link: https://download.support.siren.solutions/kibi/community?file=kibi-4.5.3-6-darwin-x64-demo-full.zip

```
unzip kibi-4.5.3-6-darwin-x64-demo-full.zip
cd kibi-4.5.3-6-darwin-x64-demo-full/elasticsearch  
bin/elasticsearch 
cd ../kibi
bin/kibi
```

Starting elasticsearch works. Starting kibi throws the same exception.

**Comment by scampi** [comment]
Can you try to remove the `kibi/optimize/bundles` folder before running `kibi/bin/kibi` ?

**Comment by danbeck** [comment]
Unfortunately, I had a bad config file in the home directory (files ~/.babel.json  ~/.babelrc)

I deleted them and kibi starts now. Thanks.

**Comment by scampi** [comment]
good to know!
