### ISSUE TITLE
Kibi 5.2.2 FATAL TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by HandsomeWins** [sirensolutions/kibi#78]
**Kibi version**: kibi-community-standalone-5.2.2-beta-1-linux-x64

**Elasticsearch version**: 5.4

**Server OS version**: SLES11 Linux

**Browser version**: Chrome

**Browser OS version**: 58.0.3029.110

**Original install method (e.g. download page, from source, etc.)**: Download from web, extract on the system as the user who will be executing binaries

**Description of the problem including expected versus actual behavior**: Can't start due to node-related issue

**Steps to reproduce**:
 1. Try to start Kibi, fail immediately

**Errors in browser console (if relevant)**: NA

**Provide logs and/or server output (if relevant)**: See below.

/elastic/kibi> bin/kibi
  log   [00:18:19.144] [fatal] TypeError: Cannot read property 'push' of undefined
    at /elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/src/server/pid/index.js:54:28
    at tryCatcher (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
FATAL TypeError: Cannot read property 'push' of undefined
    at /elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/src/server/pid/index.js:54:28
    at tryCatcher (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/elastic/kibi-community-standalone-5.2.2-beta-1-linux-x64/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by scampi** [comment]
you have to use ES 5.2.2, can you try again and say how this goes ?

**Comment by szydan** [comment]
Hi @HandsomeWins we've just released 5.4.0-beta-2
https://github.com/sirensolutions/kibi/releases/tag/tag-5.4.0-beta-2

Now you should be able to try to run it with Elasticsearch 5.4.x
