### ISSUE TITLE
Run kibi with external nodejs server

### ISSUE THREAD

**Issue by nmqhoan** [sirensolutions/kibi#8]
Hi, is that possible to run kibi with external nodejs server which is already installed? I reconfigured the kibi.sh script as follows:
# !/bin/sh

SCRIPT=$0

while [ -h "$SCRIPT" ] ; do
  ls=$(ls -ld "$SCRIPT")
  # Drop everything prior to ->
  link=$(expr "$ls" : '._-> (._)$')
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=$(dirname "$SCRIPT")/"$link"
  fi
done

DIR=$(dirname "${SCRIPT}")/..
NODE=node
SERVER=${DIR}/src/bin/kibi.js

$DIR/bin/create_symlink.sh

ROOT_DIR="$DIR/" CONFIG_PATH="${DIR}/config/kibi.yml" NODE_ENV="production" exec "${NODE}" --debug ${SERVER} ${@}

then I started the kibi application but there were a lot of "Cannot find module" exceptions thrown out.
Any help will be appreciated.

Best,

**Comment by fabiocorneti** [comment]
Hi, this is currently not supported, but I'm keeping the issue open to test the case; can you provide the following information:
- the version of the external node executable
- the full output of the script (or at least some of the exceptions you're seeing)

Thanks

**Comment by nmqhoan** [comment]
Hi, Thanks for your reply. The current version of my external nodejs is v5.0.0. Here is the full output of the script:

``` javascript
nb681:bin hoan$ ./kibi
java_home_lib_server symlink already exist
lrwxr-xr-x  1 hoan  staff  79  2 Nov 11:52 java_home_lib_server -> /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home//jre/lib/server
If you would like to override it with detected path
run the following command manually:

ln -s /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home//jre/lib/server java_home_lib_server

Debugger listening on port 5858
module.js:339
    throw err;
    ^

Error: Cannot find module '/Volumes/Data/Projects/kibi-0.1.1-demo-full-darwin-x64/kibi/src/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/Data/Projects/kibi-0.1.1-demo-full-darwin-x64/kibi/src/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/Data/Projects/kibi-0.1.1-demo-full-darwin-x64/kibi/src/lib/sindicetech/sqliteQuery.js:5:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/Data/Projects/kibi-0.1.1-demo-full-darwin-x64/kibi/src/lib/sindicetech/queryEngine.js:14:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/Data/Projects/kibi-0.1.1-demo-full-darwin-x64/kibi/src/routes/proxy.js:17:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/Data/Projects/kibi-0.1.1-demo-full-darwin-x64/kibi/src/app.js:13:13)
    at Module._compile (module.js:425:26)
```

What i was trying is to debug step by step to have a better understanding of kibi source code.
Thanks

**Comment by fabiocorneti** [comment]
I see, we currently do not support Node versions different than ~0.10/~0.12 as our project is based on Kibana 4.1; it may be possible to run it using other node versions but you would have to compile the sqlite and jdbc native bindings and some dependencies may work incorrectly.

Can you connect to the debugger port by adding the `--debug` flag to the included node binary?

**Comment by szydan** [comment]
In kibi version 0.3.0 it is possible to use a system node - but it is highly not recommended as kibi comes with sets of pre built native bindings for sqlite and jdbc - when you change the node version these packages will not work anymore.
