### ISSUE TITLE
MODULE_NOT_FOUND exception while starting kibi.bat

### ISSUE THREAD

**Issue by AliAqdasShah** [sirensolutions/kibi#94]
**master(5.5.2)**:

**5.5.2**:

**Windows7 x64**:

**Clone from git. run "npm install" in kibi directory then run kibi/bin/kibi.bat**:

**Kibi should run but i'm getting following error
*FATAL { Error: Cannot find module 'C:\ELK-repo\kibi\node_modules\sqlite3\lib\bin
ding\node-v48-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ELK-repo\kibi\node_modules\sqlite3\lib\sqlite3.js:
4:15)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ELK-repo\kibi
\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/ELK-repo/kibi/src/kibi_plugins/kibi_core/lib/queri
es/sqlite_query.js:6:1)
    at Module._compile (module.js:570:32)
    at loader (C:\ELK-repo\kibi\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ELK-repo\kibi
\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/ELK-repo/kibi/src/kibi_plugins/kibi_core/lib/query
_engine.js:15:1)
    at Module._compile (module.js:570:32)
    at loader (C:\ELK-repo\kibi\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ELK-repo\kibi
\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }*:

**Steps to reproduce**:
 1. Clone from git
 2. "npm install" in kibi folder 
 3. run.bat in kibi/bin

**FATAL { Error: Cannot find module 'C:\ELK-repo\kibi\node_modules\sqlite3\lib\bin
ding\node-v48-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ELK-repo\kibi\node_modules\sqlite3\lib\sqlite3.js:
4:15)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ELK-repo\kibi
\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/ELK-repo/kibi/src/kibi_plugins/kibi_core/lib/queri
es/sqlite_query.js:6:1)
    at Module._compile (module.js:570:32)
    at loader (C:\ELK-repo\kibi\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ELK-repo\kibi
\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/ELK-repo/kibi/src/kibi_plugins/kibi_core/lib/query
_engine.js:15:1)
    at Module._compile (module.js:570:32)
    at loader (C:\ELK-repo\kibi\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ELK-repo\kibi
\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }**:

**Provide logs and/or server output (if relevant)**:

**Comment by szydan** [comment]
Master was moved to 5.6.4
@AliAqdasShah will you be able to try it again?
